name: EST protocol tests by using curl

on:
  push:
  pull_request:
    branches: [ devel ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  est_proto_curl:
    name: "est_proto_curl"
    runs-on: ubuntu-latest
    steps:
    - name: "checkout GIT"
      uses: actions/checkout@v2

    - name: "[ PREPARE ] Build docker-compose"
      working-directory: examples/Docker/
      run: |
        sudo mkdir -p data
        docker network create est
        docker-compose up -d
        docker-compose logs

    - name: "[ PREPARE ] est-proxy config"
      run: |
        sudo cp .github/wf_data/est_proxy_basic.cfg examples/Docker/data/est_proxy.cfg
        sudo cp -R .github/wf_data/certs examples/Docker/data/
        sudo cp -R .github/wf_data/xca examples/Docker/data/
        sudo chmod 777 examples/Docker/data/est_proxy.cfg
        sudo cat .github/wf_data/est_proxy_clientauth.cfg >> examples/Docker/data/est_proxy.cfg
        sudo cat .github/wf_data/est_proxy_xca.cfg >> examples/Docker/data/est_proxy.cfg
        sudo cp .github/wf_data/certs/cacerts.pem /tmp
        sudo cp .github/wf_data/certs/estcl*.pem /tmp
        sudo chmod 755 /tmp/*.pem
        cd examples/Docker/
        docker-compose restart
        docker-compose logs

    - name: "[ Test ] fetch CA-certificates"
      run: docker run -v /tmp/cacerts.pem:/tmp/cacerts.pem -i --rm --network est curlimages/curl -X GET https://est-proxy.est:17443/.well-known/est/cacerts --cacert /tmp/cacerts.pem 

    - name: "[ Test ] enroll certificate"
      run: docker run -v /tmp/cacerts.pem:/tmp/cacerts.pem -v /tmp/estclient.crt.pem:/tmp/estclient.crt.pem -v /tmp/estclient.key.pem:/tmp/estclient.key.pem -v /tmp/estclient.csr.pem:/tmp/estclient.csr.pem -i --rm --network est curlimages/curl https://est-proxy.est:17443/.well-known/est/simpleenroll --key /tmp/estclient.key.pem --cert /tmp/estclient.crt.pem --cacert /tmp/cacerts.pem --data-binary "@/tmp/estclient.csr.pem" -H "Content-Type:application/pkcs10" --verbose

    - name: "[ * ] collecting test logs"
      if: ${{ failure() }}
      run: |
        mkdir -p ${{ github.workspace }}/artifact/upload
        sudo cp -rp examples/Docker/data/ ${{ github.workspace }}/artifact/data/
        cd examples/Docker
        docker-compose logs > ${{ github.workspace }}/artifact/docker-compose.log
        sudo tar -C ${{ github.workspace }}/artifact/ -cvzf ${{ github.workspace }}/artifact/upload/artifact.tar.gz docker-compose.log data

    - name: "[ * ] uploading artificates"
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: est_proto_curl.tar.gz
        path: ${{ github.workspace }}/artifact/upload/
